name: cs229new
channels:
  - defaults
dependencies:
  - python=3.9
  - pip=24.2
  - pip:
    - asttokens==3.0.0
    - Brotli==1.0.9
    - certifi==2025.1.31
    - cftime==1.6.4.post1
    - charset-normalizer==3.3.2
    - colorama==0.4.6
    - comm==0.2.2
    - contourpy==1.2.0
    - cycler==0.11.0
    - debugpy==1.8.12
    - decorator==5.1.1
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - fonttools==4.55.3
    - h5netcdf==1.5.0
    - h5py==3.13.0
    - idna==3.7
    - importlib_metadata==8.6.1
    - importlib_resources==6.4.0
    - ipykernel==6.29.5
    - ipython==8.18.1
    - jedi==0.19.2
    - joblib==1.4.2
    - jupyter_client==8.6.3
    - jupyter_core==5.7.2
    - kiwisolver==1.4.4
    - matplotlib==3.9.2
    - matplotlib-inline==0.1.7
    - mkl-service==2.4.0
    - nest_asyncio==1.6.0
    - netCDF4==1.7.2
    - numpy==1.23.3
    - packaging==24.2
    - pandas==2.2.3
    - parso==0.8.4
    - pickleshare==0.7.5
    - pillow==11.0.0
    - platformdirs==3.10.0
    - ply==3.11
    - pooch==1.8.2
    - prompt_toolkit==3.0.50
    - psutil==6.1.1
    - pure_eval==0.2.3
    - Pygments==2.19.1
    - pyparsing==3.2.0
    - PyQt5==5.15.10
    - PyQt5_sip==12.13.0
    - PySocks==1.7.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.1
    - pywin32==307
    - pyzmq==26.2.0
    - requests==2.32.3
    - scikit-learn==1.6.1
    - scipy==1.10.1
    - setuptools==75.1.0
    - sip==6.7.12
    - six==1.16.0
    - stack_data==0.6.3
    - threadpoolctl==3.5.0
    - tomli==2.0.1
    - tornado==6.4.2
    - traitlets==5.14.3
    # typing_extensions was removed to satisfy TensorFlow’s requirement of <4.6.0
    - tzdata==2025.1
    - unicodedata2==15.1.0
    - urllib3==2.3.0
    - wcwidth==0.2.13
    - wheel==0.44.0
    - win-inet-pton==1.1.0
    - xarray==2024.7.0
    - zipp==3.21.0
    - tensorflow==2.13.0

    # ----------------------------
    # PyTorch & related libraries
    # ----------------------------
    - torch
    - torchvision
    - torchaudio
